services:
  backend:
    build: ./backend
    container_name: img-backend-dev
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/data
    environment:
      POST_EXPIRE_TIMES_SECONDS: 60,120,240,3600,86400,604800,2592000
      POST_DEFAULT_EXPIRE_TIME_SECONDS: 120
  
  frontend:
    build: ./frontend
    container_name: img-frontend-dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
