services:
  backend:
    build:
      context: .
      target: dev
      args:
        service: backend
    command: pnpm dev
    container_name: img-backend-dev
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - ./data:/data
    environment:
      POST_EXPIRE_TIMES_SECONDS: 60,120,240,3600,86400,604800,2592000
      POST_DEFAULT_EXPIRE_TIME_SECONDS: 120
      POST_MAX_SIZE_BYTES: 209715200
      FOOTER_LINK_TITLE_DMCA: DMCA
      FOOTER_LINK_URL_DMCA: mailto:dmca@example.com
      FOOTER_LINK_TITLE_TEST: Test
      FOOTER_LINK_URL_TEST: https://example.com

  frontend:
    build:
      context: .
      target: dev
      args:
        service: frontend
    command: pnpm dev
    container_name: img-frontend-dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
