name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -E 's/refs\/tags\/v(.*)/\1/')
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            nylyk/img:${{ steps.get_version.outputs.VERSION }}
            nylyk/img:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
